---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoguo.
--- DateTime: 2020/11/18 9:34
---


local modulename = "abtestingAppConf"

local _M = {}

_M._VERSION = '0.0.1'

-- 灰度应用列表 配置
_M.grayApp = {
    "driver","carlife"
}

_M.global_configs = {
    ["divEnable"] = true,  -- 分流开关，true表示开启
    ["newTrafficRate"] = 100,  -- 分流比例，0-1000， 1000表示全部流量，100%

}

_M.redisConf = {
    --["uds"]      = '/tmp/redis.sock',
    ["host"]     = '172.18.5.110',
    ["port"]     = '6379',
    ["poolsize"] = 20000,
    ["idletime"] = 90000 ,
    ["timeout"]  = 3000,
    ["dbid"]     = 0,
    ["auth"]     = 'Yq0wHk5AmlpJ0lEleO5zsMNN6npXOQ'
}


_M.divConf = {
    ["default_backend"]     = ngx.var.default_backend,
    --["shdict_expire"]       = 60,   -- in s
    ["shdict_expire"]       = tonumber(ngx.var.shdict_expire or 120)
}


return _M