---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoguo.
--- DateTime: 2020/11/18 20:06
---

--[[
local flowRatiostrategyCache = ngx.shared.api_flow_ratio_strategy
----初始小流量计数器
local prefix = 'hostName'
flowRatiostrategyCache:set(prefix .. "_count",0)
ngx.log(ngx.DEBUG, "timer_at run worker:",ngx.worker.id())
]]











