---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoguo.
--- DateTime: 2020/11/12 16:50
---
--流量比例
local flowRatiostrategyCache = ngx.shared.api_flow_ratio_strategy
local _M = {
    _VERSION = '0.01'
}

_M.new = function(self,option)
    self.db = option.db

end

local JSHash = function(str)
    local bit = require "bit"

    local lshift = bit.lshift
    local rshift = bit.rshift
    local bxor = bit.bxor

    local byte = string.byte
    local sub = string.sub
    local len = string.len
    local l = len(str)
    local h = l
    local step = rshift(l, 5) + 1

    for i=l,step,-step do
        h = bxor(h, (lshift(h, 5) + byte(sub(str, i, i)) + rshift(h, 2)))
    end
    return h
end

_M.get = function()

    --local prefix_key = "hostName" .. "_count";
    local remoteIp = tostring(ngx.var.remote_addr)
    local numIp = string.gsub(remoteIp,"%.","",3);
    ngx.log(ngx.DEBUG,'用户请求ip:',remoteIp)
    local hashcode = JSHash(numIp)

    local ratio = hashcode % 100

    --小流量
    --local newval,err = flowRatiostrategyCache:incr(prefix_key,1)

    ngx.log(ngx.DEBUG,"请求比例:",ratio)
    if ratio  then
        return ratio
    else
        return nui;
    end
end




return _M