---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoguo.
--- DateTime: 2020/11/12 18:03
---


local utils         = require('abtesting.utils.utils')
local log			= require('abtesting.utils.log')
local ERRORINFO     = require('abtesting.error.errcode').info
local appCofig      = require('config.appConf')
local jwt           = require("resty.jwt")

local cjson         = require('cjson.safe')
local doresp        = utils.doresp
local dolog         = utils.dolog

local _M = {
    _VERSION = '0.01'
}

_M.get = function()
--[[    local request_body  = ngx.var.request_body
    local postData      = cjson.decode(request_body)
    if not request_body then
        -- ERRORCODE.PARAMETER_NONE
        local errinfo   = ERRORINFO.PARAMETER_NONE
        local desc      = 'request_body or post data'
        local response  = doresp(errinfo, desc)
        log:errlog(dolog(errinfo, desc))
        ngx.say(response)
        return nil
    end

    if not postData then
        -- ERRORCODE.PARAMETER_ERROR
        local errinfo   = ERRORINFO.PARAMETER_ERROR
        local desc      = 'postData is not a json string'
        local response  = doresp(errinfo, desc)
        log:errlog(dolog(errinfo, desc))
        ngx.say(response)
        return nil
    end
    return postData['token']]
    local jwt_token = ngx.req.get_headers()["X-Token"]

    local  tokens = string.sub(jwt_token, 8)
    ngx.log(ngx.DEBUG,tokens)

    local validToken = utils.split(tokens,";")



    ngx.log(ngx.DEBUG,validToken[1])


    local jwt_obj = jwt:verify(appCofig.jwtConfig.secret, validToken[1], 0)

    return jwt_obj
    --return ngx.req.get_headers()["X-Token"]
end
return _M