---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guoguo.
--- DateTime: 2020/11/12 16:50
---

local _M = {
    _VERSION = '0.01'
}

_M.get = function()
    return ngx.req.get_headers()["X-Version"]
end
return _M